railstutorial: "https://www.railstutorial.org/"
rubyonrails: "http://rubyonrails.org/"
railshelp: "https://www.railstutorial.org/help"
railsbook: "https://www.railstutorial.org/book"
railscon: "https://www.railstutorial.org/contact"
rubyonrailstutorial: "The Ruby on Rails Tutorial"
screen: "http://screencasts.railstutorial.org/"
mh: "http://www.michaelhartl.com/"
newrails: "http://news.railstutorial.org/"
en: en
vi: vi
max50: 50
max255: 255
min6: 6
size80: 80
size90: 90
validemailregex: !ruby/regexp '/\A[ơ\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
min1: 1
